changesDir: .changes
unreleasedDir: unreleased
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'
kinds:
    - label: FEATURES
      auto: minor
    - label: BREAKING CHANGES
      auto: major
    - label: ENHANCEMENTS
      auto: minor
    - label: BUG FIXES
      auto: patch
    - label: NOTES
      auto: none
newlines:
    afterChangelogHeader: 1
    beforeChangelogVersion: 1
    endOfVersion: 1
envPrefix: CHANGIE_
